"""
=============================================================================
STORAGE - Database for Encrypted Messages (PostgreSQL / SQLite)
=============================================================================

This module provides the Storage class for persisting:
1. Encrypted emails (local mailbox)
2. Pending messages (server broker queue)

DATABASE BACKENDS:
------------------
- **Production**: PostgreSQL (set DATABASE_URL env var)
  - Schema-based user isolation (each user gets their own schema)
  - Connection pooling with pool_pre_ping for resilience
  - Auto-creates schemas for per-user databases
- **Development**: SQLite (default fallback)
  - Per-file database (one SQLite file per user)
  - WAL mode for better concurrent access

DATABASE SCHEMA:
----------------

┌─────────────────────────────────────────────────────────────────────────┐
│  TABLE: emails (local mailbox)                                          │
├─────────────────────────────────────────────────────────────────────────┤
│  id                  INTEGER PRIMARY KEY  -- Unique email ID            │
│  sender              TEXT                 -- Sender email address       │
│  recipient           TEXT                 -- Recipient email address    │
│  subject             TEXT                 -- Email subject (encrypted?) │
│  ciphertext          BLOB                 -- Encrypted message body     │
│  mac                 BLOB (nullable)      -- MAC tag (for OTP)          │
│  signature           BLOB (nullable)      -- PQC digital signature      │
│  signature_algorithm TEXT (nullable)      -- e.g., "Dilithium2"         │
│  sent_at             DATETIME             -- When message was sent      │
│  view_once           BOOLEAN              -- Is this a view-once msg?   │
│  viewed              BOOLEAN              -- Has it been viewed?        │
│  otp_key             BLOB (nullable)      -- OTP key (view-once only)   │
│  mac_key             BLOB (nullable)      -- MAC key (view-once only)   │
│  key_exchange_mode   TEXT                 -- "pqc" or "bb84"            │
│  encryption_mode     TEXT                 -- "aes" or "view_once_otp"   │
│  folder              TEXT                 -- Inbox, Sent, Drafts, Trash │
│  delivery_status     TEXT                 -- sent, delivered, read      │
│  delivered_at        DATETIME (nullable)  -- When delivered             │
│  read_at             DATETIME (nullable)  -- When read                  │
│  server_message_id   TEXT (nullable)      -- UUID for broker tracking   │
└─────────────────────────────────────────────────────────────────────────┘

┌─────────────────────────────────────────────────────────────────────────┐
│  TABLE: pending_messages (server broker queue)                          │
├─────────────────────────────────────────────────────────────────────────┤
│  id                     TEXT PRIMARY KEY  -- UUID generated by sender   │
│  sender                 TEXT              -- Sender email               │
│  recipient              TEXT              -- Recipient email            │
│  subject                TEXT              -- Subject line               │
│  encrypted_content      BLOB              -- Encrypted message body     │
│  encryption_type        TEXT              -- "aes" or "otp"             │
│  key_material           BLOB              -- Session key or OTP keys    │
│  mac                    BLOB (nullable)   -- MAC tag                    │
│  signature              BLOB (nullable)   -- PQC signature              │
│  signature_algorithm    TEXT (nullable)   -- Signature algorithm        │
│  key_exchange_algorithm TEXT              -- "pqc" or "bb84"            │
│  view_once              BOOLEAN           -- View-once flag             │
│  status                 TEXT              -- pending, acknowledged      │
│  created_at             DATETIME          -- When uploaded              │
│  downloaded_at          DATETIME (null)   -- When recipient downloaded  │
│  acknowledged_at        DATETIME (null)   -- When receipt confirmed     │
└─────────────────────────────────────────────────────────────────────────┘

SECURITY NOTES:
---------------
1. CIPHERTEXT ONLY: The `ciphertext` column stores encrypted data.
   Plaintext is NEVER written to the database.

2. VIEW-ONCE KEYS: For OTP-encrypted messages, the `otp_key` and `mac_key`
   are temporarily stored until first viewing. After viewing:
   - The `viewed` flag is set to True
   - Keys should be zeroized in memory
   - The message can never be decrypted again

3. KEY MATERIAL: The `key_material` column in `pending_messages` stores
   the session key (for AES) or OTP keys (for OTP). This is encrypted
   during transit using PQC key exchange.

4. SIGNATURES: PQC signatures are stored to enable verification even
   after message delivery, providing non-repudiation.

USAGE:
------
    from qmail.storage.db import Storage

    # Production (PostgreSQL):
    storage = Storage(database_url="postgresql://user:pass@localhost/qmail")

    # Per-user isolation with PostgreSQL schemas:
    storage = Storage(
        database_url="postgresql://user:pass@localhost/qmail",
        schema="user_alice_at_qmail_com",
    )

    # Development (SQLite - backward compatible):
    from pathlib import Path
    storage = Storage(db_path=Path("mailbox.db"))

    # Save an email
    email_id = storage.save_email(email_envelope)

    # Get an email
    email = storage.get_email(email_id)

    # List all emails
    for email in storage.list_emails():

    # Server broker operations
    storage.save_pending_message(...)
    messages = storage.list_pending_messages("recipient@example.com")
    storage.mark_message_downloaded("message-uuid")
    storage.delete_pending_message("message-uuid")
"""

from __future__ import annotations

import base64
import os
import re
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, Optional

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from sqlalchemy import (
    LargeBinary,
    Boolean,
    Column,
    DateTime,
    Integer,
    MetaData,
    String,
    Table,
    create_engine,
    event,
    select,
    insert,
    delete,
    text,
)
from sqlalchemy.engine import Engine

from qmail.models import EmailEnvelope, EncryptionMode

# ---------------------------------------------------------------------------
# Engine cache — avoids creating a new connection pool on every request.
# Thread-safe via a lock; keyed on (database_url, schema).
# ---------------------------------------------------------------------------
_engine_cache: Dict[str, Engine] = {}
_engine_lock = threading.Lock()


metadata = MetaData()

emails_table = Table(
    "emails",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("sender", String, nullable=False),
    Column("recipient", String, nullable=False),
    Column("subject", String, nullable=False),
    Column("ciphertext", LargeBinary, nullable=False),
    Column("mac", LargeBinary, nullable=True),
    Column("signature", LargeBinary, nullable=True),
    Column("signature_algorithm", String, nullable=True),
    Column("sent_at", DateTime, nullable=False),
    Column("view_once", Boolean, nullable=False, default=False),
    Column("viewed", Boolean, nullable=False, default=False),  # True after first view for view-once emails
    Column("otp_key", LargeBinary, nullable=True),  # For view-once OTP decryption
    Column("mac_key", LargeBinary, nullable=True),  # For view-once MAC verification
    Column("key_exchange_mode", String, nullable=False),
    Column("encryption_mode", String, nullable=False),
    Column("folder", String, nullable=False, default="Inbox"),  # "Inbox", "Sent", "Drafts", "Trash"
    # WhatsApp-style delivery tracking (sent, delivered, read)
    Column("delivery_status", String, nullable=False, default="sent"),  # sent, delivered, read
    Column("delivered_at", DateTime, nullable=True),  # When recipient downloaded
    Column("read_at", DateTime, nullable=True),  # When recipient read
    Column("server_message_id", String, nullable=True),  # UUID for server-side temporary storage
    Column("in_reply_to", String, nullable=True),  # ID of the email being replied to (for threading)
)

# WhatsApp-style server message broker
# Messages stored temporarily (not archived), deleted after delivery acknowledgment
# Flow: sender uploads → server queues → recipient downloads → recipient acknowledges → server deletes
pending_messages_table = Table(
    "pending_messages",
    metadata,
    Column("id", String, primary_key=True),  # UUID generated by sender (server_message_id)
    Column("sender", String, nullable=False),
    Column("recipient", String, nullable=False),
    Column("subject", String, nullable=False),
    Column("encrypted_content", LargeBinary, nullable=False),  # Encrypted (AES or OTP)
    Column("encryption_type", String, nullable=False),  # "aes", "otp"
    Column("key_material", LargeBinary, nullable=False),  # ML-KEM encapsulated session key (TRUE E2E - broker can't see plaintext key)
    Column("mac", LargeBinary, nullable=True),  # MAC tag for integrity
    Column("signature", LargeBinary, nullable=True),  # PQC digital signature
    Column("signature_algorithm", String, nullable=True),
    Column("key_exchange_algorithm", String, nullable=False),  # e.g., "pqc", "bb84"
    Column("view_once", Boolean, nullable=False, default=False),
    Column("status", String, nullable=False, default="pending"),  # pending, acknowledged, deleted
    Column("created_at", DateTime, nullable=False),
    Column("downloaded_at", DateTime, nullable=True),  # When recipient downloaded
    Column("acknowledged_at", DateTime, nullable=True),  # When recipient confirmed receipt
    Column("attachments_json", String, nullable=True),  # JSON serialized attachments with base64 data
    Column("in_reply_to", String, nullable=True),  # ID of the email being replied to (for threading)
    # No expires_at - auto-delete on acknowledgment within reasonable time (e.g., 72h for safety)
)

# Attachments table - stores file attachments for emails
attachments_table = Table(
    "attachments",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("email_id", Integer, nullable=False),  # Foreign key to emails table
    Column("filename", String, nullable=False),
    Column("mime_type", String, nullable=False),
    Column("size_bytes", Integer, nullable=False),
    Column("data", LargeBinary, nullable=False),  # File content (always encrypted with AES-GCM)
    Column("encryption_key_hex", String, nullable=True),  # AES-256 key in hex (64 chars)
    Column("created_at", DateTime, nullable=False),
)

# PQC Signing Keys table - stores Dilithium2/Falcon keypairs for digital signatures
# Public keys are shared via broker for signature verification
# Private keys NEVER leave the user's device storage
signing_keys_table = Table(
    "signing_keys",
    metadata,
    Column("email", String, primary_key=True),  # User email as identifier
    Column("public_key", LargeBinary, nullable=False),  # PQC public key (safe to share)
    Column("private_key", LargeBinary, nullable=True),  # PQC private key (only in user's local DB, NULL in broker)
    Column("algorithm", String, nullable=False, default="Dilithium2"),  # "Dilithium2" or "Falcon-512"
    Column("created_at", DateTime, nullable=False),
    Column("updated_at", DateTime, nullable=True),  # When key was rotated
)

# ML-KEM Encryption Keys table - stores ML-KEM-1024 keypairs for TRUE E2E encryption
# Public keys are shared via broker so senders can encapsulate session keys
# Private keys NEVER leave the user's device - used to decapsulate received session keys
# This ensures the broker CANNOT read session keys (true E2E security)
kem_keys_table = Table(
    "kem_keys",
    metadata,
    Column("email", String, primary_key=True),  # User email as identifier
    Column("public_key", LargeBinary, nullable=False),  # ML-KEM-1024 public key (~1,568 bytes, safe to share)
    Column("private_key", LargeBinary, nullable=True),  # ML-KEM-1024 secret key (only in user's local DB, NULL in broker)
    Column("algorithm", String, nullable=False, default="ML-KEM-1024"),  # "ML-KEM-1024"
    Column("created_at", DateTime, nullable=False),
    Column("updated_at", DateTime, nullable=True),  # When key was rotated
)

# Users table - stores @qmail.com account information
# Phone-verified signup: name, DOB, phone → OTP verification → account creation
users_table = Table(
    "users",
    metadata,
    Column("id", String, primary_key=True),  # Unique user ID (e.g., usr_abc123xyz)
    Column("username", String, unique=True, nullable=False),  # Username (3-20 chars)
    Column("qmail_address", String, unique=True, nullable=False),  # username@qmail.com
    Column("name", String, nullable=False),  # Full name
    Column("date_of_birth", String, nullable=False),  # ISO format (YYYY-MM-DD)
    Column("phone_number", String, unique=True, nullable=False),  # E.164 format - one phone per account
    Column("phone_number_verified", Boolean, nullable=False, default=False),  # After OTP verification
    Column("password_hash", String, nullable=True),  # bcrypt/argon2 hash (set after OTP verification)
    Column("is_active", Boolean, nullable=False, default=True),  # Account status
    Column("account_created_at", DateTime, nullable=False),  # Registration timestamp
    Column("password_set_at", DateTime, nullable=True),  # When password was first set
    Column("last_login_at", DateTime, nullable=True),  # Last login time
    Column("updated_at", DateTime, nullable=True),  # Last update
)

# OTP Sessions table - tracks OTP verification attempts
# Flow: request OTP → get session_id → user enters OTP → verify OTP with session_id → create account
otp_sessions_table = Table(
    "otp_sessions",
    metadata,
    Column("otp_session_id", String, primary_key=True),  # Unique session ID (e.g., sess_abc123xyz)
    Column("phone_number", String, nullable=False),  # Phone number for routing OTP
    Column("otp_code_hash", String, nullable=False),  # bcrypt hash of OTP (NOT plaintext)
    Column("user_metadata_json", String, nullable=False),  # JSON: {name, dob, phone_original, country_code}
    Column("verification_attempts", Integer, nullable=False, default=0),  # Failed attempts
    Column("max_attempts", Integer, nullable=False, default=3),  # Max failed attempts before session expires
    Column("is_verified", Boolean, nullable=False, default=False),  # True after successful OTP verification
    Column("created_at", DateTime, nullable=False),  # Session creation time
    Column("expires_at", DateTime, nullable=False),  # OTP expires after 10 minutes
    Column("verified_at", DateTime, nullable=True),  # When OTP was successfully verified
)

# Password Reset Tokens table - for forgot password flow
password_reset_tokens_table = Table(
    "password_reset_tokens",
    metadata,
    Column("token", String, primary_key=True),  # Unique reset token
    Column("user_id", String, nullable=False),  # Reference to user
    Column("email", String, nullable=False),  # User's @qmail.com address
    Column("created_at", DateTime, nullable=False),
    Column("expires_at", DateTime, nullable=False),  # Valid for 1 hour
    Column("used_at", DateTime, nullable=True),  # When password was reset
)


class Storage:
    """
    Encrypted local storage abstraction.

    NOTE: This stores ciphertext only; key material must be handled separately.
    
    DB ENCRYPTION AT REST:
    ----------------------
    When an `encryption_key` (32 bytes) is provided, sensitive fields are
    transparently encrypted with AES-256-GCM before being written to the
    database and decrypted when read back:
    
    - emails.subject        → AES-256-GCM encrypted (base64 TEXT)
    - pending_messages.subject → AES-256-GCM encrypted (base64 TEXT)
    - signing_keys.private_key → AES-256-GCM encrypted (BLOB)
    - kem_keys.private_key     → AES-256-GCM encrypted (BLOB)
    
    Searchable fields (sender, recipient) are NOT encrypted because they
    are used in WHERE clauses. They are already contextually protected:
    - User DBs are per-user (scoped by email / schema)
    - Broker DB recipient/sender are needed for message routing
    
    The encryption key should be stored in the OS keyring (not on disk).
    """

    # Prefix for encrypted text fields to distinguish from legacy plaintext
    _ENC_PREFIX = "ENC:"

    def __init__(
        self,
        db_path: Optional[Path] = None,
        encryption_key: Optional[bytes] = None,
        *,
        database_url: Optional[str] = None,
        schema: Optional[str] = None,
    ) -> None:
        """
        Create a Storage instance.

        Args:
            db_path: Path to a SQLite database file (legacy / development).
                     Ignored when *database_url* is supplied.
            encryption_key: Optional 32-byte AES key for field-level encryption.
            database_url: Full SQLAlchemy database URL.
                          - ``postgresql://user:pass@host/db`` for production.
                          - ``sqlite:///path.db`` for development.
                          Falls back to ``sqlite:///{db_path}`` when omitted.
            schema: PostgreSQL schema name for user isolation (ignored for SQLite).
                    When provided the schema is created automatically and every
                    connection from this Storage sets ``search_path`` to it.
        """
        self._encryption_key = encryption_key
        self._schema = schema

        # Resolve database URL
        if database_url is None:
            if db_path is None:
                raise ValueError("Either database_url or db_path must be provided")
            database_url = f"sqlite:///{db_path}"

        self._is_sqlite = database_url.startswith("sqlite")
        self._engine = self._get_or_create_engine(database_url, schema)

        # SQLite-specific optimisations (WAL, busy timeout)
        if self._is_sqlite:
            with self._engine.connect() as conn:
                conn.execute(text("PRAGMA journal_mode=WAL"))
                conn.execute(text("PRAGMA busy_timeout=30000"))
                conn.commit()

        # Ensure schema exists (PostgreSQL only)
        if not self._is_sqlite and schema:
            safe_schema = re.sub(r"[^a-zA-Z0-9_]", "_", schema)
            with self._engine.begin() as conn:
                conn.execute(text(f'CREATE SCHEMA IF NOT EXISTS "{safe_schema}"'))

        metadata.create_all(self._engine, checkfirst=True)
        # Run migrations for schema updates
        self._migrate_schema()

    # ------------------------------------------------------------------
    # Engine cache (class-level, thread-safe)
    # ------------------------------------------------------------------
    @staticmethod
    def _get_or_create_engine(database_url: str, schema: Optional[str] = None) -> Engine:
        """Return a cached or newly created SQLAlchemy Engine."""
        cache_key = f"{database_url}|{schema or 'public'}"
        with _engine_lock:
            if cache_key in _engine_cache:
                return _engine_cache[cache_key]

        is_sqlite = database_url.startswith("sqlite")

        if is_sqlite:
            engine = create_engine(
                database_url,
                connect_args={"timeout": 30, "check_same_thread": False},
            )
        else:
            # PostgreSQL — use connection pooling
            engine = create_engine(
                database_url,
                pool_size=10,
                max_overflow=20,
                pool_pre_ping=True,
                pool_recycle=1800,  # recycle connections every 30 min
            )
            # Bind every connection to the requested schema
            if schema:
                safe_schema = re.sub(r"[^a-zA-Z0-9_]", "_", schema)

                @event.listens_for(engine, "connect")
                def _set_search_path(dbapi_conn, connection_record):
                    cursor = dbapi_conn.cursor()
                    cursor.execute(f'SET search_path TO "{safe_schema}", public')
                    cursor.close()

        with _engine_lock:
            _engine_cache[cache_key] = engine
        return engine

    # -------------------------------------------------------------------------
    # Field-level encryption helpers (AES-256-GCM)
    # -------------------------------------------------------------------------

    def _encrypt_text(self, plaintext: str) -> str:
        """Encrypt a text field. Returns 'ENC:<base64(nonce+ciphertext)>' or plaintext if no key."""
        if not self._encryption_key or not plaintext:
            return plaintext
        nonce = os.urandom(12)
        aesgcm = AESGCM(self._encryption_key)
        ct = aesgcm.encrypt(nonce, plaintext.encode("utf-8"), None)
        return self._ENC_PREFIX + base64.b64encode(nonce + ct).decode("ascii")

    def _decrypt_text(self, stored: str) -> str:
        """Decrypt a text field. Handles both encrypted ('ENC:...') and legacy plaintext."""
        if not stored:
            return stored
        if not stored.startswith(self._ENC_PREFIX):
            return stored  # Legacy plaintext — return as-is
        if not self._encryption_key:
            return stored  # No key available — return raw (shouldn't happen)
        raw = base64.b64decode(stored[len(self._ENC_PREFIX):])
        nonce, ct = raw[:12], raw[12:]
        aesgcm = AESGCM(self._encryption_key)
        return aesgcm.decrypt(nonce, ct, None).decode("utf-8")

    def _encrypt_blob(self, data: Optional[bytes]) -> Optional[bytes]:
        """Encrypt a BLOB field. Returns nonce+ciphertext or original if no key."""
        if not self._encryption_key or data is None:
            return data
        nonce = os.urandom(12)
        aesgcm = AESGCM(self._encryption_key)
        ct = aesgcm.encrypt(nonce, data, None)
        # Prefix with magic bytes 'EBLB' so we can detect encrypted blobs
        return b"EBLB" + nonce + ct

    def _decrypt_blob(self, stored: Optional[bytes]) -> Optional[bytes]:
        """Decrypt a BLOB field. Handles both encrypted ('EBLB...') and legacy plaintext."""
        if stored is None:
            return None
        if not stored[:4] == b"EBLB":
            return stored  # Legacy unencrypted blob
        if not self._encryption_key:
            return stored  # No key — return raw
        nonce = stored[4:16]
        ct = stored[16:]
        aesgcm = AESGCM(self._encryption_key)
        return aesgcm.decrypt(nonce, ct, None)

    def _safe_add_column(self, conn, table_name: str, column_name: str, col_type: str, default: str = None) -> None:
        """Safely add a column if it doesn't exist (works for both SQLite and PostgreSQL)."""
        try:
            conn.execute(text(f"SELECT {column_name} FROM {table_name} LIMIT 1"))
        except Exception:
            try:
                default_clause = f" DEFAULT {default}" if default else ""
                conn.execute(text(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {col_type}{default_clause}"))
            except Exception:
                pass

    def _migrate_schema(self) -> None:
        """
        Handle schema migrations for database updates.
        This allows adding new columns without losing existing data.
        Works for both SQLite and PostgreSQL.
        """
        # Use BYTEA for PostgreSQL, BLOB for SQLite
        blob_type = "BYTEA" if not self._is_sqlite else "BLOB"

        with self._engine.begin() as conn:
            # Emails table migrations
            self._safe_add_column(conn, "emails", "viewed", "BOOLEAN NOT NULL", "FALSE")
            self._safe_add_column(conn, "emails", "otp_key", blob_type)
            self._safe_add_column(conn, "emails", "mac_key", blob_type)
            self._safe_add_column(conn, "emails", "delivery_status", "VARCHAR NOT NULL", "'sent'")
            self._safe_add_column(conn, "emails", "delivered_at", "TIMESTAMP")
            self._safe_add_column(conn, "emails", "read_at", "TIMESTAMP")
            self._safe_add_column(conn, "emails", "server_message_id", "VARCHAR")
            self._safe_add_column(conn, "emails", "signature", blob_type)
            self._safe_add_column(conn, "emails", "signature_algorithm", "VARCHAR")
            self._safe_add_column(conn, "emails", "in_reply_to", "VARCHAR")

            # Pending messages table migrations
            self._safe_add_column(conn, "pending_messages", "attachments_json", "TEXT")
            self._safe_add_column(conn, "pending_messages", "signature", blob_type)
            self._safe_add_column(conn, "pending_messages", "signature_algorithm", "VARCHAR")
            self._safe_add_column(conn, "pending_messages", "in_reply_to", "VARCHAR")

            # Attachments table migrations
            self._safe_add_column(conn, "attachments", "encryption_key_hex", "VARCHAR")

            # Clean up orphaned attachments (where email_id doesn't exist)
            try:
                orphan_cleanup = text("""
                    DELETE FROM attachments 
                    WHERE email_id NOT IN (SELECT id FROM emails)
                """)
                conn.execute(orphan_cleanup)
            except Exception:
                pass

    def save_email(self, email: EmailEnvelope) -> int:
        with self._engine.begin() as conn:
            stmt = (
                insert(emails_table)
                .values(
                    sender=email.sender,
                    recipient=email.recipient,
                    subject=self._encrypt_text(email.subject),
                    ciphertext=email.ciphertext,
                    mac=email.mac,
                    signature=email.signature,
                    signature_algorithm=email.signature_algorithm,
                    sent_at=email.sent_at,
                    view_once=email.view_once,
                    viewed=email.viewed,
                    otp_key=email.otp_key,
                    mac_key=email.mac_key,
                    key_exchange_mode=email.key_exchange_mode,
                    encryption_mode=email.encryption_mode.value,
                    folder=email.folder,
                    delivery_status="sent",  # WhatsApp-style: starts as sent
                    server_message_id=getattr(email, 'server_message_id', None),
                    in_reply_to=getattr(email, 'in_reply_to', None),
                )
            )
            result = conn.execute(stmt)
            return int(result.inserted_primary_key[0])

    def list_emails(self) -> Iterable[EmailEnvelope]:
        with self._engine.connect() as conn:
            stmt = select(emails_table).order_by(emails_table.c.sent_at.desc())
            rows = conn.execute(stmt)
            for row in rows:
                yield EmailEnvelope(
                    id=row.id,
                    sender=row.sender,
                    recipient=row.recipient,
                    subject=self._decrypt_text(row.subject),
                    ciphertext=row.ciphertext,
                    mac=row.mac,
                    signature=row.signature,
                    signature_algorithm=row.signature_algorithm,
                    sent_at=row.sent_at,
                    view_once=row.view_once,
                    viewed=row.viewed,
                    otp_key=row.otp_key if hasattr(row, 'otp_key') else None,
                    mac_key=row.mac_key if hasattr(row, 'mac_key') else None,
                    key_exchange_mode=row.key_exchange_mode,
                    encryption_mode=EncryptionMode(row.encryption_mode),
                    folder=row.folder,
                    delivery_status=row.delivery_status if hasattr(row, 'delivery_status') else 'sent',
                    delivered_at=row.delivered_at if hasattr(row, 'delivered_at') else None,
                    read_at=row.read_at if hasattr(row, 'read_at') else None,
                    server_message_id=row.server_message_id if hasattr(row, 'server_message_id') else None,
                    in_reply_to=row.in_reply_to if hasattr(row, 'in_reply_to') else None,
                )

    def get_email(self, email_id: int) -> Optional[EmailEnvelope]:
        with self._engine.connect() as conn:
            stmt = select(emails_table).where(emails_table.c.id == email_id)
            row = conn.execute(stmt).fetchone()
            if row is None:
                return None
            return EmailEnvelope(
                id=row.id,
                sender=row.sender,
                recipient=row.recipient,
                subject=self._decrypt_text(row.subject),
                ciphertext=row.ciphertext,
                mac=row.mac,
                signature=row.signature,
                signature_algorithm=row.signature_algorithm,
                sent_at=row.sent_at,
                view_once=row.view_once,
                viewed=row.viewed,
                otp_key=row.otp_key if hasattr(row, 'otp_key') else None,
                mac_key=row.mac_key if hasattr(row, 'mac_key') else None,
                key_exchange_mode=row.key_exchange_mode,
                encryption_mode=EncryptionMode(row.encryption_mode),
                folder=row.folder,
                delivery_status=row.delivery_status if hasattr(row, 'delivery_status') else 'sent',
                delivered_at=row.delivered_at if hasattr(row, 'delivered_at') else None,
                read_at=row.read_at if hasattr(row, 'read_at') else None,
                server_message_id=row.server_message_id if hasattr(row, 'server_message_id') else None,
                in_reply_to=row.in_reply_to if hasattr(row, 'in_reply_to') else None,
            )

    def delete_email(self, email_id: int) -> bool:
        """
        Permanently delete an email row by ID, including all attachments.

        Returns True if a row was deleted, False if no such ID existed.
        """
        with self._engine.begin() as conn:
            # First delete associated attachments (cascade)
            att_stmt = delete(attachments_table).where(attachments_table.c.email_id == email_id)
            att_result = conn.execute(att_stmt)
            if att_result.rowcount > 0:
                pass
            
            # Then delete the email itself
            stmt = delete(emails_table).where(emails_table.c.id == email_id)
            result = conn.execute(stmt)
            return result.rowcount > 0

    def mark_email_viewed(self, email_id: int) -> bool:
        """
        Mark a view-once email as viewed (one-time view enforcement).
        
        Returns True if the email was updated, False if it doesn't exist.
        For view-once emails, this ensures they cannot be decrypted again.
        """
        with self._engine.begin() as conn:
            stmt = (
                emails_table.update()
                .where(emails_table.c.id == email_id)
                .values(viewed=True)
            )
            result = conn.execute(stmt)
            return result.rowcount > 0

    def update_delivery_status(self, email_id: int, status: str, timestamp: Optional[datetime] = None) -> bool:
        """
        WhatsApp-style: Update delivery status (sent, delivered, read).
        """
        with self._engine.begin() as conn:
            values = {"delivery_status": status}
            if status == "delivered" and timestamp:
                values["delivered_at"] = timestamp
            elif status == "read" and timestamp:
                values["read_at"] = timestamp
            
            stmt = (
                emails_table.update()
                .where(emails_table.c.id == email_id)
                .values(**values)
            )
            result = conn.execute(stmt)
            return result.rowcount > 0

    def update_email_content(self, email_id: int, decrypted_content: bytes) -> bool:
        """
        Update the email's ciphertext field with decrypted content.
        
        This is called after successful decryption to store the plaintext,
        so future reads (like inbox preview) can display the actual content.
        
        Returns True if the email was updated, False if it doesn't exist.
        """
        with self._engine.begin() as conn:
            stmt = (
                emails_table.update()
                .where(emails_table.c.id == email_id)
                .values(ciphertext=decrypted_content)
            )
            result = conn.execute(stmt)
            return result.rowcount > 0

    def update_email_folder(self, email_id: int, folder: str) -> bool:
        """
        Update the email's folder field.
        
        Used for moving emails between folders (e.g., move to Trash).
        
        Returns True if the email was updated, False if it doesn't exist.
        """
        with self._engine.begin() as conn:
            stmt = (
                emails_table.update()
                .where(emails_table.c.id == email_id)
                .values(folder=folder)
            )
            result = conn.execute(stmt)
            return result.rowcount > 0

    def update_draft(self, email_id: int, recipient: str, subject: str, content: bytes) -> bool:
        """
        Update a draft's recipient, subject, and content.
        
        Returns True if the draft was updated, False if it doesn't exist.
        """
        with self._engine.begin() as conn:
            stmt = (
                emails_table.update()
                .where(emails_table.c.id == email_id)
                .values(
                    recipient=recipient,
                    subject=self._encrypt_text(subject),
                    ciphertext=content
                )
            )
            result = conn.execute(stmt)
            return result.rowcount > 0

    # Attachment methods
    
    def save_attachment(
        self,
        email_id: int,
        filename: str,
        mime_type: str,
        size_bytes: int,
        data: bytes,
        encryption_key_hex: Optional[str] = None,
    ) -> int:
        """Save an attachment for an email. Returns the attachment ID.
        
        Args:
            email_id: The email this attachment belongs to
            filename: Original filename
            mime_type: MIME type of the file
            size_bytes: Original file size (before encryption)
            data: Encrypted file content (AES-GCM: nonce + ciphertext + tag)
            encryption_key_hex: AES-256 key in hex format (64 chars)
        """
        with self._engine.begin() as conn:
            stmt = (
                insert(attachments_table)
                .values(
                    email_id=email_id,
                    filename=filename,
                    mime_type=mime_type,
                    size_bytes=size_bytes,
                    data=data,
                    encryption_key_hex=encryption_key_hex,
                    created_at=datetime.now(timezone.utc),
                )
            )
            result = conn.execute(stmt)
            return int(result.inserted_primary_key[0])

    def get_attachments(self, email_id: int) -> list:
        """Get all attachments for an email."""
        with self._engine.connect() as conn:
            stmt = select(attachments_table).where(
                attachments_table.c.email_id == email_id
            )
            rows = conn.execute(stmt)
            return [
                {
                    "id": row.id,
                    "email_id": row.email_id,
                    "filename": row.filename,
                    "mime_type": row.mime_type,
                    "size_bytes": row.size_bytes,
                    "data": row.data,
                    "encryption_key_hex": getattr(row, 'encryption_key_hex', None),
                }
                for row in rows
            ]

    def get_attachment(self, attachment_id: int) -> Optional[dict]:
        """Get a single attachment by ID."""
        with self._engine.connect() as conn:
            stmt = select(attachments_table).where(
                attachments_table.c.id == attachment_id
            )
            row = conn.execute(stmt).fetchone()
            if row is None:
                return None
            return {
                "id": row.id,
                "email_id": row.email_id,
                "filename": row.filename,
                "mime_type": row.mime_type,
                "size_bytes": row.size_bytes,
                "data": row.data,
                "encryption_key_hex": getattr(row, 'encryption_key_hex', None),
            }

    def delete_attachments(self, email_id: int) -> int:
        """Delete all attachments for an email. Returns count deleted."""
        with self._engine.begin() as conn:
            stmt = delete(attachments_table).where(
                attachments_table.c.email_id == email_id
            )
            result = conn.execute(stmt)
            return result.rowcount

    # WhatsApp-style server message broker (transient, not persistent)
    # Messages queued temporarily, deleted on acknowledgment

    def save_pending_message(
        self,
        message_id: str,
        sender: str,
        recipient: str,
        subject: str,
        encrypted_content: bytes,
        encryption_type: str,  # "aes" or "otp"
        key_material: bytes,  # Session key (AES) or OTP keys (OTP)
        mac: Optional[bytes],
        signature: Optional[bytes],
        signature_algorithm: Optional[str],
        key_exchange_algorithm: str,
        view_once: bool = False,
    ) -> None:
        """
        Save a message to the server broker queue.
        Message will be delivered to recipient and then deleted.
        """
        with self._engine.begin() as conn:
            conn.execute(
                pending_messages_table.insert().values(
                    id=message_id,
                    sender=sender,
                    recipient=recipient,
                    subject=self._encrypt_text(subject),
                    encrypted_content=encrypted_content,
                    encryption_type=encryption_type,
                    key_material=key_material,
                    mac=mac,
                    signature=signature,
                    signature_algorithm=signature_algorithm,
                    key_exchange_algorithm=key_exchange_algorithm,
                    view_once=view_once,
                    status="pending",
                    created_at=datetime.utcnow(),
                )
            )

    def get_pending_message(self, message_id: str) -> Optional[dict]:
        """
        Retrieve a pending message from the broker queue.
        """
        with self._engine.connect() as conn:
            stmt = select(pending_messages_table).where(
                pending_messages_table.c.id == message_id
            )
            row = conn.execute(stmt).fetchone()
            if row is None:
                return None
            return {
                "id": row.id,
                "sender": row.sender,
                "recipient": row.recipient,
                "subject": self._decrypt_text(row.subject),
                "encrypted_content": row.encrypted_content,
                "encryption_type": row.encryption_type,
                "key_material": row.key_material,
                "mac": row.mac,
                "signature": row.signature,
                "signature_algorithm": row.signature_algorithm,
                "key_exchange_algorithm": row.key_exchange_algorithm,
                "view_once": row.view_once,
                "status": row.status,
                "created_at": row.created_at,
                "downloaded_at": row.downloaded_at,
                "acknowledged_at": row.acknowledged_at,
            }

    def list_pending_messages(self, recipient: str) -> list[dict]:
        """
        List all pending messages for a recipient (WhatsApp-style broker queue).
        """
        with self._engine.connect() as conn:
            stmt = (
                select(pending_messages_table)
                .where(pending_messages_table.c.recipient == recipient)
                .where(pending_messages_table.c.status == "pending")
            )
            rows = conn.execute(stmt).fetchall()
            return [
                {
                    "id": row.id,
                    "sender": row.sender,
                    "subject": self._decrypt_text(row.subject),
                    "view_once": row.view_once,
                    "created_at": row.created_at,
                }
                for row in rows
            ]

    def mark_message_downloaded(self, message_id: str) -> bool:
        """
        Mark a message as downloaded by recipient.
        """
        with self._engine.begin() as conn:
            stmt = (
                pending_messages_table.update()
                .where(pending_messages_table.c.id == message_id)
                .values(status="acknowledged", downloaded_at=datetime.utcnow(), acknowledged_at=datetime.utcnow())
            )
            result = conn.execute(stmt)
            return result.rowcount > 0

    def delete_pending_message(self, message_id: str) -> bool:
        """
        Delete a message from server broker queue (auto-cleanup after acknowledgment).
        """
        with self._engine.begin() as conn:
            stmt = (
                pending_messages_table.delete()
                .where(pending_messages_table.c.id == message_id)
            )
            result = conn.execute(stmt)
            return result.rowcount > 0

    def get_pending_message_status(self, sender: str, message_id: str) -> Optional[dict]:
        """
        Get the status of a message for the sender (WhatsApp-style delivery tracking).
        """
        with self._engine.connect() as conn:
            stmt = (
                select(pending_messages_table)
                .where(pending_messages_table.c.id == message_id)
                .where(pending_messages_table.c.sender == sender)
            )
            row = conn.execute(stmt).fetchone()
            if row is None:
                return None
            return {
                "id": row.id,
                "recipient": row.recipient,
                "status": row.status,
                "created_at": row.created_at,
                "downloaded_at": row.downloaded_at,
                "acknowledged_at": row.acknowledged_at,
            }

    # -------------------------------------------------------------------------
    # PQC Signing Keys Management
    # -------------------------------------------------------------------------

    def save_signing_keypair(
        self,
        email: str,
        public_key: bytes,
        private_key: Optional[bytes],
        algorithm: str = "Dilithium2",
    ) -> None:
        """
        Save or update a PQC signing keypair.
        
        For local storage: stores both public and private keys.
        For broker storage: stores only public key (private_key=None).
        """
        encrypted_pk = self._encrypt_blob(private_key)
        now = datetime.now(timezone.utc)
        with self._engine.begin() as conn:
            # Try to update existing key first
            stmt = (
                signing_keys_table.update()
                .where(signing_keys_table.c.email == email)
                .values(
                    public_key=public_key,
                    private_key=encrypted_pk,
                    algorithm=algorithm,
                    updated_at=now,
                )
            )
            result = conn.execute(stmt)
            
            # If no existing key, insert new one
            if result.rowcount == 0:
                stmt = signing_keys_table.insert().values(
                    email=email,
                    public_key=public_key,
                    private_key=encrypted_pk,
                    algorithm=algorithm,
                    created_at=now,
                    updated_at=None,
                )
                conn.execute(stmt)

    def get_signing_keypair(self, email: str) -> Optional[dict]:
        """
        Retrieve a signing keypair by email.
        
        Returns dict with 'public_key', 'private_key' (if available), 'algorithm'.
        """
        with self._engine.connect() as conn:
            stmt = select(signing_keys_table).where(signing_keys_table.c.email == email)
            row = conn.execute(stmt).fetchone()
            if row is None:
                return None
            return {
                "email": row.email,
                "public_key": row.public_key,
                "private_key": self._decrypt_blob(row.private_key),
                "algorithm": row.algorithm,
                "created_at": row.created_at,
                "updated_at": row.updated_at,
            }

    def get_public_key(self, email: str) -> Optional[tuple[bytes, str]]:
        """
        Get just the public key and algorithm for a user.
        
        Returns (public_key_bytes, algorithm) or None if not found.
        """
        keypair = self.get_signing_keypair(email)
        if keypair is None:
            return None
        return (keypair["public_key"], keypair["algorithm"])

    # =========================================================================
    # ML-KEM Encryption Key Methods (for TRUE E2E session key encryption)
    # =========================================================================

    def save_kem_keypair(
        self,
        email: str,
        public_key: bytes,
        private_key: Optional[bytes],
        algorithm: str = "ML-KEM-1024",
    ) -> None:
        """
        Save or update an ML-KEM encryption keypair.
        
        For local storage: stores both public and private keys.
        For broker storage: stores only public key (private_key=None).
        
        This is used for TRUE E2E encryption - the session key is encapsulated
        using the recipient's ML-KEM public key, ensuring only they can decrypt.
        """
        encrypted_pk = self._encrypt_blob(private_key)
        now = datetime.now(timezone.utc)
        with self._engine.begin() as conn:
            # Try to update existing key first
            stmt = (
                kem_keys_table.update()
                .where(kem_keys_table.c.email == email)
                .values(
                    public_key=public_key,
                    private_key=encrypted_pk,
                    algorithm=algorithm,
                    updated_at=now,
                )
            )
            result = conn.execute(stmt)
            
            # If no existing key, insert new one
            if result.rowcount == 0:
                stmt = kem_keys_table.insert().values(
                    email=email,
                    public_key=public_key,
                    private_key=encrypted_pk,
                    algorithm=algorithm,
                    created_at=now,
                    updated_at=None,
                )
                conn.execute(stmt)

    def get_kem_keypair(self, email: str) -> Optional[dict]:
        """
        Retrieve an ML-KEM keypair by email.
        
        Returns dict with 'public_key', 'private_key' (if available), 'algorithm'.
        """
        with self._engine.connect() as conn:
            stmt = select(kem_keys_table).where(kem_keys_table.c.email == email)
            row = conn.execute(stmt).fetchone()
            if row is None:
                return None
            return {
                "email": row.email,
                "public_key": row.public_key,
                "private_key": self._decrypt_blob(row.private_key),
                "algorithm": row.algorithm,
                "created_at": row.created_at,
                "updated_at": row.updated_at,
            }

    def get_kem_public_key(self, email: str) -> Optional[tuple[bytes, str]]:
        """
        Get just the ML-KEM public key and algorithm for a user.
        
        Returns (public_key_bytes, algorithm) or None if not found.
        Used by senders to encapsulate session keys for recipients.
        """
        keypair = self.get_kem_keypair(email)
        if keypair is None:
            return None
        return (keypair["public_key"], keypair["algorithm"])

    # -------------------------------------------------------------------------
    # User Account Management (Phone-Verified Signup)
    # -------------------------------------------------------------------------

    def create_user(
        self,
        user_id: str,
        username: str,
        qmail_address: str,
        name: str,
        date_of_birth: str,
        phone_number: str,
        password_hash: str,
    ) -> dict:
        """
        Create a new @qmail.com user account after OTP verification.
        
        Args:
            user_id: Unique user ID (e.g., usr_abc123xyz)
            username: Username (3-20 chars, will be username@qmail.com)
            qmail_address: Full email address (username@qmail.com)
            name: Full name
            date_of_birth: ISO format (YYYY-MM-DD)
            phone_number: E.164 format
            password_hash: bcrypt hash of password
        
        Returns:
            User dict with all account details
        """
        now = datetime.now(timezone.utc)
        with self._engine.begin() as conn:
            stmt = users_table.insert().values(
                id=user_id,
                username=username,
                qmail_address=qmail_address,
                name=name,
                date_of_birth=date_of_birth,
                phone_number=phone_number,
                phone_number_verified=True,
                password_hash=password_hash,
                is_active=True,
                account_created_at=now,
                password_set_at=now,
                last_login_at=None,
                updated_at=now,
            )
            conn.execute(stmt)
        
        return self.get_user_by_id(user_id)

    def get_user_by_id(self, user_id: str) -> Optional[dict]:
        """Retrieve user by user_id."""
        with self._engine.connect() as conn:
            stmt = select(users_table).where(users_table.c.id == user_id)
            row = conn.execute(stmt).fetchone()
            if row is None:
                return None
            return {
                "id": row.id,
                "username": row.username,
                "qmail_address": row.qmail_address,
                "password_hash": row.password_hash,
                "name": row.name,
                "date_of_birth": row.date_of_birth,
                "phone_number": row.phone_number,
                "phone_number_verified": row.phone_number_verified,
                "is_active": row.is_active,
                "account_created_at": row.account_created_at,
                "password_set_at": row.password_set_at,
                "last_login_at": row.last_login_at,
                "updated_at": row.updated_at,
            }

    def get_user_by_qmail_address(self, qmail_address: str) -> Optional[dict]:
        """Retrieve user by @qmail.com email address."""
        with self._engine.connect() as conn:
            stmt = select(users_table).where(
                users_table.c.qmail_address == qmail_address.lower()
            )
            row = conn.execute(stmt).fetchone()
            if row is None:
                return None
            return {
                "id": row.id,
                "username": row.username,
                "qmail_address": row.qmail_address,
                "password_hash": row.password_hash,
                "name": row.name,
                "date_of_birth": row.date_of_birth,
                "phone_number": row.phone_number,
                "phone_number_verified": row.phone_number_verified,
                "is_active": row.is_active,
                "account_created_at": row.account_created_at,
                "password_set_at": row.password_set_at,
                "last_login_at": row.last_login_at,
                "updated_at": row.updated_at,
            }

    def get_user_by_username(self, username: str) -> Optional[dict]:
        """Retrieve user by username."""
        with self._engine.connect() as conn:
            stmt = select(users_table).where(
                users_table.c.username == username.lower()
            )
            row = conn.execute(stmt).fetchone()
            if row is None:
                return None
            return {
                "id": row.id,
                "username": row.username,
                "qmail_address": row.qmail_address,
                "password_hash": row.password_hash,
                "name": row.name,
                "date_of_birth": row.date_of_birth,
                "phone_number": row.phone_number,
                "phone_number_verified": row.phone_number_verified,
                "is_active": row.is_active,
                "account_created_at": row.account_created_at,
                "password_set_at": row.password_set_at,
                "last_login_at": row.last_login_at,
                "updated_at": row.updated_at,
            }

    def update_last_login(self, user_id: str) -> None:
        """Update last login timestamp."""
        now = datetime.now(timezone.utc)
        with self._engine.begin() as conn:
            stmt = (
                users_table.update()
                .where(users_table.c.id == user_id)
                .values(last_login_at=now, updated_at=now)
            )
            conn.execute(stmt)

    def check_username_available(self, username: str) -> bool:
        """Check if username is available (not already taken)."""
        with self._engine.connect() as conn:
            stmt = select(users_table).where(
                users_table.c.username == username.lower()
            )
            row = conn.execute(stmt).fetchone()
            return row is None

    def check_phone_available(self, phone_number: str) -> bool:
        """Check if phone number is available (not already registered to an account)."""
        with self._engine.connect() as conn:
            stmt = select(users_table).where(
                users_table.c.phone_number == phone_number
            )
            row = conn.execute(stmt).fetchone()
            return row is None

    def get_user_by_phone(self, phone_number: str) -> Optional[dict]:
        """Retrieve user by phone number."""
        with self._engine.connect() as conn:
            stmt = select(users_table).where(
                users_table.c.phone_number == phone_number
            )
            row = conn.execute(stmt).fetchone()
            if row is None:
                return None
            return {
                "id": row.id,
                "username": row.username,
                "qmail_address": row.qmail_address,
                "password_hash": row.password_hash,
                "name": row.name,
                "date_of_birth": row.date_of_birth,
                "phone_number": row.phone_number,
                "phone_number_verified": row.phone_number_verified,
                "is_active": row.is_active,
                "account_created_at": row.account_created_at,
                "password_set_at": row.password_set_at,
                "last_login_at": row.last_login_at,
                "updated_at": row.updated_at,
            }

    def get_user_by_email(self, email: str) -> Optional[dict]:
        """Retrieve user by email address (alias for get_user_by_qmail_address)."""
        return self.get_user_by_qmail_address(email)

    def update_user_password(self, user_id: str, password_hash: str) -> None:
        """
        Update user's password hash.
        
        Args:
            user_id: User ID (from 'id' field, not 'user_id')
            password_hash: bcrypt hash of new password
        """
        now = datetime.now(timezone.utc)
        with self._engine.begin() as conn:
            stmt = (
                users_table.update()
                .where(users_table.c.id == user_id)
                .values(
                    password_hash=password_hash,
                    password_set_at=now,
                    updated_at=now,
                )
            )
            conn.execute(stmt)

    # -------------------------------------------------------------------------
    # OTP Session Management
    # -------------------------------------------------------------------------

    def create_otp_session(
        self,
        otp_session_id: str,
        phone_number: str,
        otp_code_hash: str,
        user_metadata_json: str,
        expires_at: datetime,
    ) -> dict:
        """
        Create a new OTP verification session.
        
        Args:
            otp_session_id: Unique session ID
            phone_number: E.164 formatted phone
            otp_code_hash: bcrypt hash of OTP (NOT plaintext)
            user_metadata_json: JSON with {name, dob, phone_original, country_code}
            expires_at: When OTP expires (usually 10 minutes from now)
        
        Returns:
            OTP session dict
        """
        now = datetime.now(timezone.utc)
        with self._engine.begin() as conn:
            stmt = otp_sessions_table.insert().values(
                otp_session_id=otp_session_id,
                phone_number=phone_number,
                otp_code_hash=otp_code_hash,
                user_metadata_json=user_metadata_json,
                verification_attempts=0,
                max_attempts=3,
                is_verified=False,
                created_at=now,
                expires_at=expires_at,
                verified_at=None,
            )
            conn.execute(stmt)
        
        return self.get_otp_session(otp_session_id)

    def get_otp_session(self, otp_session_id: str) -> Optional[dict]:
        """Retrieve OTP session details."""
        with self._engine.connect() as conn:
            stmt = select(otp_sessions_table).where(
                otp_sessions_table.c.otp_session_id == otp_session_id
            )
            row = conn.execute(stmt).fetchone()
            if row is None:
                return None
            return {
                "otp_session_id": row.otp_session_id,
                "phone_number": row.phone_number,
                "otp_code_hash": row.otp_code_hash,
                "user_metadata_json": row.user_metadata_json,
                "verification_attempts": row.verification_attempts,
                "max_attempts": row.max_attempts,
                "is_verified": row.is_verified,
                "created_at": row.created_at,
                "expires_at": row.expires_at,
                "verified_at": row.verified_at,
            }

    def increment_otp_attempt(self, otp_session_id: str) -> int:
        """
        Increment failed OTP verification attempts.
        
        Returns:
            Updated attempt count
        """
        with self._engine.begin() as conn:
            stmt = (
                otp_sessions_table.update()
                .where(otp_sessions_table.c.otp_session_id == otp_session_id)
                .values(verification_attempts=otp_sessions_table.c.verification_attempts + 1)
            )
            conn.execute(stmt)
        
        session = self.get_otp_session(otp_session_id)
        return session["verification_attempts"] if session else 0

    def mark_otp_verified(self, otp_session_id: str) -> None:
        """Mark OTP session as successfully verified."""
        now = datetime.now(timezone.utc)
        with self._engine.begin() as conn:
            stmt = (
                otp_sessions_table.update()
                .where(otp_sessions_table.c.otp_session_id == otp_session_id)
                .values(is_verified=True, verified_at=now)
            )
            conn.execute(stmt)

    def update_otp_session_metadata(self, otp_session_id: str, user_metadata_json: str) -> None:
        """
        Update metadata for an OTP session (useful for password reset context).
        
        Args:
            otp_session_id: Session ID
            user_metadata_json: Updated JSON metadata
        """
        with self._engine.begin() as conn:
            stmt = (
                otp_sessions_table.update()
                .where(otp_sessions_table.c.otp_session_id == otp_session_id)
                .values(user_metadata_json=user_metadata_json)
            )
            conn.execute(stmt)
